// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('find_work', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  // afterEach(async function() {
  //   await driver.quit();
  // })
  it('find_work', async function() {
    await driver.get("https://jobs.dou.ua/")
    await driver.manage().window().setRect(1440, 900)
    await driver.findElement(By.css("li > .sel")).click()
    {
      const dropdown = await driver.findElement(By.name("category"))
      await dropdown.findElement(By.xpath("//option[. = 'QA']")).click()
    }
    await driver.findElement(By.css("option:nth-child(31)")).click()
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.name("search")).sendKeys("junor QA")
    await driver.findElement(By.css(".btn-search")).click()
    await driver.close()
  })
})