// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  it('test', async function() {
    await driver.get("https://dou.ua/")
    await driver.manage().window().setRect(1440, 900)
    await driver.findElement(By.css(".b-head li:nth-child(6) > a")).click()
    {
      const dropdown = await driver.findElement(By.name("category"))
      await dropdown.findElement(By.xpath("//option[. = 'QA']")).click()
    }
    await driver.findElement(By.css("option:nth-child(31)")).click()
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.name("search")).sendKeys("junor QA")
    await driver.findElement(By.css(".btn-search")).click()

    await driver.close()
  })

  it('forum_news', async function() {
    await driver.get("https://dou.ua/")
    await driver.manage().window().setRect(1440, 900)
    await driver.findElement(By.css(".b-head li:nth-child(3) > a")).click()
    {
      const dropdown = await driver.findElement(By.name("topic"))
      await dropdown.findElement(By.xpath("//option[. = 'Новости']")).click()
    }
    await driver.findElement(By.css("option:nth-child(4)")).click()

    await driver.close()
  })

  it('salary', async function() {
    await driver.get("https://dou.ua/")
    await driver.manage().window().setRect(1440, 900)
    await driver.findElement(By.css(".b-head li:nth-child(5) > a")).click()
    {
      const dropdown = await driver.findElement(By.name("city"))
      await dropdown.findElement(By.xpath("//option[. = 'Одесса']")).click()
    }
    await driver.findElement(By.css(".salarydec-field:nth-child(2) option:nth-child(16)")).click()
    {
      const dropdown = await driver.findElement(By.name("title"))
      await dropdown.findElement(By.xpath("//option[. = 'Junior QA engineer']")).click()
    }
    await driver.findElement(By.css(".qa:nth-child(1)")).click()
    
    await driver.close()
  })
})